services:
  rag:
    build: ./
    container_name: rag
    depends_on:
      - chroma
    ports:
      - "8080:8080"
    volumes:
      - ocr_texts:/var/lib/rag/ocr_texts
    restart: on-failure:5

  chroma:
    image: ghcr.io/chroma-core/chroma:0.5.23
    container_name: chroma
    ports:
      - "8000:8000"
    environment:
      CHROMA_ANONYMOUS_TELEMETRY_ENABLED: "false"
    volumes:
      - vector_data:/chroma/chroma
    restart: on-failure:5

volumes:
  vector_data:
    driver: local
  ocr_texts:
    driver: local